server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/studysync
spring.datasource.username=studysync_user
spring.datasource.password=Studysync2026!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

